### ISSUE TITLE
TDFV==0.14.0 Wheel Fails Integrity Check

### ISSUE THREAD

**Issue by jhamet93** [tensorflow/data-validation#78] opened 2019-08-12 17:36 UTC
It appears `TFDV==0.14.0` has a bad hash value and is failing the integrity check done by the resolver, `pex`:

`Exception message: Bad hash for file 'tensorflow_data_validation/pywrap/_pywrap_tensorflow_data_validation.so'`.

It has been reported (https://github.com/pypa/pip/issues/4705) that pip does not check the file hashes for integrity but other resolvers such as Pex do which leads to failures.  Thus, it appears there's some mutation after the wheel is built ? 

Minimal Repo:
```
pip install pex
pex tensorflow-data-validation==0.14.0 -o tfdv.pex
```

**Comment by rmothukuru** [comment] 2019-08-13 06:22
@jhamet93 ,
I have tried reproducing your issue with the Repro Code provided by you in Linux Terminal but I didn't get the Exception Message which you got. 

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow and version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by paulgc** [comment] 2019-08-13 18:17
We can verify that the wheel is failing the check by doing:

`wheel unpack tensorflow_data_validation-0.14.0-cp27-cp27mu-manylinux2010_x86_64.whl`

Unpacking to: ./tensorflow_data_validation-0.14.0...Hash mismatch for file 'tensorflow_data_validation/pywrap/_pywrap_tensorflow_data_validation.so'

**Comment by rmothukuru** [comment] 2019-08-20 06:33
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by jhamet93** [comment] 2019-08-20 16:23
@rmothukuru Sorry I did not respond. The comment above is a way to reproducing the issue at hand which is the package fails the integrity check because there's a modification after the wheel is built.

`wheel unpack tensorflow_data_validation-0.14.0-cp27-cp27mu-manylinux2010_x86_64.whl`

`Unpacking to: ./tensorflow_data_validation-0.14.0...Hash mismatch for file 'tensorflow_data_validation/pywrap/_pywrap_tensorflow_data_validation.so'`

**Comment by caveness** [comment] 2019-08-20 16:47
Re-opening this issue. We have verified this failure and plan to have a 0.14.1 release out soon that will address it. We will close this bug when that release is out.

**Comment by kwlzn** [comment] 2019-08-20 18:41
thanks a ton @caveness! this is blocking our adoption of TFDV at Twitter, so we're happy to help kick tires on a release candidate wheel binary if that would be useful before cutting to pypi - otherwise we'll keep an eye out for the next official release.

**Comment by paulgc** [comment] 2019-08-20 18:43
@kwlzn 0.14.1 should be out within the next few days.

**Comment by paulgc** [comment] 2019-08-22 00:42
Closing this as 0.14.1 is released.

@kwlzn @jhamet93 Let us know if you face any other issues.

**Closed by paulgc** 2019-08-22 00:42 UTC
Labels: stat:awaiting response, type:support
