### ISSUE TITLE
TFDV - slice_functions in StatsOptions creates no slices

### ISSUE THREAD

**Issue by ConverJens** [tensorflow/data-validation#142] opened 2020-10-06 12:57 UTC
I'm running a TFX pipeline using TFX 0.24.0 with an ImportExampleGen and StatisticsGen component.

I'm trying to configure slice_functions for the StatisticsGen component but it gives no result. The overall dataset statistics is computed and works as expected.

My sample dataset has five features: name, ts, datetime, duration and uniq. The code for the StatisticsGen component looks like the following:

`slice_name = slicing_util.get_feature_value_slicer(features={'name': None})`
`stats_options = tfdv.StatsOptions(slice_functions=[slice_name_raw])`
`statistics_gen = StatisticsGen(examples=example_gen.outputs['examples'], stats_options=stats_options)`

Loading and visualizing the stats artifact works as expected:
`stats = tfdv.load_statistics(os.path.join(artifact.uri, "train", "stats_tfrecord"))`
`tfdv.visualize_statistics(stats)`

However, trying to fetch a slice of the stats fails:
`tfdv.get_slice_stats(stats, 'name')'
'---------------------------------------------------------------------------`
`ValueError                                Traceback (most recent call last)`
`<ipython-input-21-f5836823d287> in <module>`
`----> 1 tfdv.get_slice_stats(stats, 'name')`
`~/pyenv/lib/python3.7/site-packages/tensorflow_data_validation/utils/stats_util.py in get_slice_stats(statistics, slice_key)`
`    315       result.datasets.add().CopyFrom(slice_stats)`
`    316       return result`
`--> 317   raise ValueError('Invalid slice key.')`
`    318 `
`    319 `
`ValueError: Invalid slice key.`

The issue seems to be that the additional slices are never generated:
`len(stats.datasets)`
yields 1 and
`len(stats.datasets[0].features)`
yields 5.

Running the pipeline in KubeFlow or interactive_context yields the same result.

Any help with this would be appreciated!

**Comment by ConverJens** [comment] 2020-10-06 15:38
Also tried this in colab using the https://www.tensorflow.org/tfx/tutorials/mlmd/mlmd_tutorial#top_of_page as a base and added a slice function but with the exact same result. There is still only the overall dataset present, no slice datasets are added to the stats_tfrecord proto.

**Comment by brills** [comment] 2020-10-16 16:55
This is a duplicate of https://github.com/tensorflow/tfx/issues/2637 .

**Comment by arghyaganguly** [comment] 2021-03-17 11:22
issue being tracked in tensorflow/tfx#2637.Closing this here.

**Closed by arghyaganguly** 2021-03-17 11:22 UTC
Labels: stat:awaiting tensorflower, type:support
